// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rstexocnpvtxfhqbnetn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzdGV4b2NucHZ0eGZocWJuZXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDczNTAsImV4cCI6MjA2MTc4MzM1MH0.CsicR5dHymzW01oviJ9DFwyTESTk3_JEV79ZnWxUUM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);